include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - camel_case_types
    - library_names
    - avoid_empty_else
    - unnecessary_brace_in_string_interps
    - avoid_redundant_argument_values
    - prefer_const_constructors
    - prefer_final_fields