name: brainer_flutter
description: earn against others
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  provider: ^6.0.5
  sign_in_with_apple: ^6.0.0
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.4
  flutter_local_notifications: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true