name: brainer_flutter
description: earn against others
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^6.0.0
  flutter_facebook_auth: ^6.0.4
  flutter_local_notifications: ^17.2.1+2
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.2
  firebase_auth: ^5.1.3
  aad_oauth: ^0.3.0
  firebase_messaging: ^15.0.4
  google_sign_in: ^6.1.6
  provider: ^6.0.5
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.4
  cloud_firestore: ^5.2.0
  github_sign_in: ^0.0.5-dev.4  
  sign_button: ^2.0.2
  linkedin_login: ^2.0.1 
  shared_preferences: ^2.0.13
  http: ^0.13.3
  sign_in_with_apple: ^6.0.0
  flutter_config: ^2.0.2
  url_launcher: ^6.1.10
  kakao_flutter_sdk: ^1.4.2
  flutter_sms: ^2.3.3
  flutter_email_sender: ^5.2.0
  twitter_login: ^4.4.0
  flutter_line_sdk: ^2.3.5
  flex_color_scheme: ^7.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/times-new-roman.ttf
