// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9T9cKSOBbrWFt1ILMw_Jjb1PDdqtvCHI',
    appId: '1:471309772132:web:357859d38029a8af824671',
    messagingSenderId: '471309772132',
    projectId: 'brainer-ac992',
    authDomain: 'brainer-ac992.firebaseapp.com',
    storageBucket: 'brainer-ac992.appspot.com',
    measurementId: 'G-M3GWY5MVED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW1zpLBI2aODaHEj8eGMdXKT_YRdyaePQ',
    appId: '1:471309772132:android:01e46e1410d28115824671',
    messagingSenderId: '471309772132',
    projectId: 'brainer-ac992',
    storageBucket: 'brainer-ac992.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYiGimowoKP1vYTt0V4TDLml_7XNhS7o',
    appId: '1:471309772132:ios:8e510d6e4e00b7e4824671',
    messagingSenderId: '471309772132',
    projectId: 'brainer-ac992',
    storageBucket: 'brainer-ac992.appspot.com',
    iosBundleId: 'com.example.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADYiGimowoKP1vYTt0V4TDLml_7XNhS7o',
    appId: '1:471309772132:ios:8e510d6e4e00b7e4824671',
    messagingSenderId: '471309772132',
    projectId: 'brainer-ac992',
    storageBucket: 'brainer-ac992.appspot.com',
    iosBundleId: 'com.example.ios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9T9cKSOBbrWFt1ILMw_Jjb1PDdqtvCHI',
    appId: '1:471309772132:web:bf0ef2a531a15dbc824671',
    messagingSenderId: '471309772132',
    projectId: 'brainer-ac992',
    authDomain: 'brainer-ac992.firebaseapp.com',
    storageBucket: 'brainer-ac992.appspot.com',
    measurementId: 'G-ZEXQCCJ9JP',
  );
}
